### ISSUE TITLE
Change Links In Footer #2

### ISSUE THREAD

**Issue by thinkorsink** [thinkorsink/vtdigs#2]
![4e909b2c-28ef-434c-b5ec-0a342d21b072](https://cloud.githubusercontent.com/assets/788180/17194611/d5233920-5426-11e6-884a-4fa4c7cb19d4.png)

**Comment by thinkorsink** [comment]
ABOUT THIS RACE (IT IS A LITTLE MORE SPECIFIC THAN THAT) ABOUT MATT DUNNE? TAGGED MATT DUNNE?

CHANGE 'BY' TO 'ABOUT' Conflicts with directions in Issue #1

"READ ALL" See Issue #1

**Comment by dianezeigler** [comment]
I now understand where I contradicted myself. The changes you made are good and this is ready to go except for one thing. As you noted in the other footer issue which I have closed because it was confusing (my fault) you said you could add a read more link to VTDigger news articles **for candidate pages**.  Please do.
![screen shot 2016-07-28 at 12 27 58 pm](https://cloud.githubusercontent.com/assets/20703702/17220788/d2d4f288-54be-11e6-8e09-cbcb722d7fdc.png)

**Comment by thinkorsink** [comment]
FIXED!
